apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos-apache
  labels:
    app: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: httpd
        image: docker.io/centos/httpd
        ports:
        - containerPort: 8080